version: "3"
services:
  ehrbase:
    image: tornadoalert/ehrbase:latest
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/ehrbase"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_AQLCONFIG_USEJSQUERY: "false"
      SERVER_NODENAME: "localhost"
      WEB_CORS_ALLOWEDORIGINPATTERNS: "*"
      WEB_CORS_ALLOWEDMETHODS: "GET,PUT,DELETE,POST,OPTIONS"
      WEB_CORS_ALLOWCREDENTIALS: "true"
      DB_USER_ADMIN: postgres
      DB_PASS_ADMIN: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
  db:
    image: postgres:13.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./cloud-db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
